/********************************************************************************************************************************/
/* Created: 29-Jun-2016 17:05:40 by OpenVMS SDL EV2-3      */
/* Source:  29-JUN-2016 17:05:39 DISK$SYSMAN:[LAISHEV.WORK.SFTU]SFTU_MSG.SDL;8 */
/********************************************************************************************************************************/
/*** MODULE $SFTDEF ***/
#ifndef __SFTDEF_LOADED
#define __SFTDEF_LOADED 1
 
#pragma __nostandard			 /* This file uses non-ANSI-Standard features */
#pragma __member_alignment __save
#pragma __nomember_alignment
#ifdef __INITIAL_POINTER_SIZE			 /* Defined whenever ptr size pragmas supported */
#pragma __required_pointer_size __save		 /* Save the previously-defined required ptr size */
#pragma __required_pointer_size __short		 /* And set ptr size default to 32-bit pointers */
#endif
 
#ifdef __cplusplus
    extern "C" {
#define __unknown_params ...
#define __optional_params ...
#else
#define __unknown_params
#define __optional_params ...
#endif
 
#ifndef __struct
#if !defined(__VAXC)
#define __struct struct
#else
#define __struct variant_struct
#endif
#endif
 
#ifndef __union
#if !defined(__VAXC)
#define __union union
#else
#define __union variant_union
#endif
#endif
 
/*                                                                          */
/* This SDL File Generated by VAX-11 Message V04-00 on 29-JUN-2016 17:05:40.04 */
/*                                                                          */
/*++                                                                        */
/*----------------------------------------------------------------------------------- */
/*	SERVER SPECIFIC MESSAGE SECTION                                     */
/*----------------------------------------------------------------------------------- */
/*--                                                                        */
#define SFTU_FACILITY 2101
/*$FIRST		<First MSG marker.>                                 */
#define SFTU_ACCEPT 137723915
#define SFTU_LISTEN 137723923
/*.EXPLANATION	 NONE.                                                      */
/*.USER_ACTION	 NONE.                                                      */
#define SFTU_RCVPUT 137723931
/*.EXPLANATION	 NONE.                                                      */
/*.USER_ACTION	 NONE.                                                      */
#define SFTU_SNDPUT 137723939
/*.EXPLANATION	 NONE.                                                      */
/*.USER_ACTION	 NONE.                                                      */
#define SFTU_RCVACK 137723947
/*.EXPLANATION	 NONE.                                                      */
/*.USER_ACTION	 NONE.                                                      */
#define SFTU_SENDING 137723955
/*.EXPLANATION	 NONE.                                                      */
/*.USER_ACTION	 NONE.                                                      */
#define SFTU_SENT 137723963
/*.EXPLANATION	 NONE.                                                      */
/*.USER_ACTION	 NONE.                                                      */
#define SFTU_ALREADY 137723971
/*.EXPLANATION	 NONE.                                                      */
/*.USER_ACTION	 NONE.                                                      */
#define SFTU_$LAST 137723979
/*.LITERAL	NUMSG=(SFTU_$LAST@--3)  !--(SFTU_$FIRST@-3)                 */
 
#pragma __member_alignment __restore
#ifdef __INITIAL_POINTER_SIZE			 /* Defined whenever ptr size pragmas supported */
#pragma __required_pointer_size __restore		 /* Restore the previously-defined required ptr size */
#endif
#ifdef __cplusplus
    }
#endif
#pragma __standard
 
#endif /* __SFTDEF_LOADED */
 
